name: Minecraft Bedrock Server
on: workflow_dispatch

jobs:
  run-server:
    runs-on: windows-latest
    steps:
    - name: Tải Minecraft Bedrock Server
      run: |
        curl -L -o bedrock-server-1.26.43.1.zip https://www.minecraft.net/bedrockdedicatedserver/bin-linux/bedrock-server-1.26.43.1.zip -DestinationPath server
    - name: Cài đặt và Chạy ngrok mở cổng 19132
      run: |
        choco install ngrok
        ngrok config add-authtoken ${{ secrets.NGROK_AUTH_TOKEN }}
        Start-Process ngrok -ArgumentList "udp 19132"
    - name: Khởi chạy Server
      run: |
        cd server
        ./bedrock_server.exe
